import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const revalidate = 2;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="Сімпсони без реклами" />
        <meta name="keywords" content="Сімпсони, без реклами, без реклами, без реклами" />
        <meta name="author" content="Сімпсони без реклами" />
        <meta name="robots" content="index, follow" />
        <meta name="google" content="notranslate" />
        <title>Сімпсони без реклами</title>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col text-gray-800 dark:bg-black dark:text-gray-400`}
      >
        <header>
          <div className="container px-8 mx-auto xl:px-5  max-w-(--breakpoint-lg) py-5 lg:py-8 relative">
            <Link
              href="/simpsons"
              className="py-2 text-lg font-medium text-gray-600 hover:text-blue-500 dark:text-gray-400"
            >
              Simpsons
            </Link>
          </div>
        </header>
        <main className="flex-1">
          <div className="container px-8 mx-auto xl:px-5  max-w-(--breakpoint-lg) relative">
            {children}
          </div>
        </main>
        <footer>
          <div className="container px-8 mx-auto xl:px-5  max-w-(--breakpoint-lg) py-5 lg:py-8 relative">
            {/* <p>Footer</p> */}
          </div>
        </footer>
      </body>
    </html>
  );
}
